export {
  PROJECT_DETAILS,
  PROJECT_FILTERS,
  PROJECT_GALLERIES,
  PROJECT_LISTING_ITEMS,
  PROJECT_PILLARS,
  PROJECT_RELATIONS,
  PROJECT_TIMELINE,
  getGalleryForCategory,
  getProjectBySlug,
} from "./data/projects";
