/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as EstimateCalculatorRouteImport } from './routes/estimate-calculator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects.$projectSlug'
import { Route as ProjectsAzureHorizonVillaRouteImport } from './routes/projects.azure-horizon-villa'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesDesignDrawingsRouteImport } from './routes/services.design-drawings'
import { Route as ServicesInteriorDesignRouteImport } from './routes/services.interior-design'
import { Route as ServicesProjectManagementRouteImport } from './routes/services.project-management'
import { Route as ServicesQualityControlRouteImport } from './routes/services.quality-control'
import { Route as ServicesQuantitySurveyingRouteImport } from './routes/services.quantity-surveying'
import { Route as ServicesRenovationRouteImport } from './routes/services.renovation'
import { Route as ServicesResidentialRouteImport } from './routes/services.residential'
import { Route as ServicesSiteSupervisionRouteImport } from './routes/services.site-supervision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateCalculatorRoute = EstimateCalculatorRouteImport.update({
  id: '/estimate-calculator',
  path: '/estimate-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/projects/$projectSlug',
  path: '/projects/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAzureHorizonVillaRoute =
  ProjectsAzureHorizonVillaRouteImport.update({
    id: '/projects/azure-horizon-villa',
    path: '/projects/azure-horizon-villa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDesignDrawingsRoute = ServicesDesignDrawingsRouteImport.update({
  id: '/services/design-drawings',
  path: '/services/design-drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInteriorDesignRoute = ServicesInteriorDesignRouteImport.update({
  id: '/services/interior-design',
  path: '/services/interior-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProjectManagementRoute =
  ServicesProjectManagementRouteImport.update({
    id: '/services/project-management',
    path: '/services/project-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesQualityControlRoute = ServicesQualityControlRouteImport.update({
  id: '/services/quality-control',
  path: '/services/quality-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesQuantitySurveyingRoute =
  ServicesQuantitySurveyingRouteImport.update({
    id: '/services/quantity-surveying',
    path: '/services/quantity-surveying',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRenovationRoute = ServicesRenovationRouteImport.update({
  id: '/services/renovation',
  path: '/services/renovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/services/residential',
  path: '/services/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSiteSupervisionRoute = ServicesSiteSupervisionRouteImport.update({
  id: '/services/site-supervision',
  path: '/services/site-supervision',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/estimate-calculator': typeof EstimateCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/projects/azure-horizon-villa': typeof ProjectsAzureHorizonVillaRoute
  '/services/design-drawings': typeof ServicesDesignDrawingsRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/services/project-management': typeof ServicesProjectManagementRoute
  '/services/quality-control': typeof ServicesQualityControlRoute
  '/services/quantity-surveying': typeof ServicesQuantitySurveyingRoute
  '/services/renovation': typeof ServicesRenovationRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/site-supervision': typeof ServicesSiteSupervisionRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/estimate-calculator': typeof EstimateCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/projects/azure-horizon-villa': typeof ProjectsAzureHorizonVillaRoute
  '/services/design-drawings': typeof ServicesDesignDrawingsRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/services/project-management': typeof ServicesProjectManagementRoute
  '/services/quality-control': typeof ServicesQualityControlRoute
  '/services/quantity-surveying': typeof ServicesQuantitySurveyingRoute
  '/services/renovation': typeof ServicesRenovationRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/site-supervision': typeof ServicesSiteSupervisionRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/estimate-calculator': typeof EstimateCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/projects/azure-horizon-villa': typeof ProjectsAzureHorizonVillaRoute
  '/services/design-drawings': typeof ServicesDesignDrawingsRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/services/project-management': typeof ServicesProjectManagementRoute
  '/services/quality-control': typeof ServicesQualityControlRoute
  '/services/quantity-surveying': typeof ServicesQuantitySurveyingRoute
  '/services/renovation': typeof ServicesRenovationRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/site-supervision': typeof ServicesSiteSupervisionRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/estimate-calculator'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/projects/$projectSlug'
    | '/projects/azure-horizon-villa'
    | '/services/design-drawings'
    | '/services/interior-design'
    | '/services/project-management'
    | '/services/quality-control'
    | '/services/quantity-surveying'
    | '/services/renovation'
    | '/services/residential'
    | '/services/site-supervision'
    | '/projects/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/estimate-calculator'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/projects/$projectSlug'
    | '/projects/azure-horizon-villa'
    | '/services/design-drawings'
    | '/services/interior-design'
    | '/services/project-management'
    | '/services/quality-control'
    | '/services/quantity-surveying'
    | '/services/renovation'
    | '/services/residential'
    | '/services/site-supervision'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-us'
    | '/estimate-calculator'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/projects/$projectSlug'
    | '/projects/azure-horizon-villa'
    | '/services/design-drawings'
    | '/services/interior-design'
    | '/services/project-management'
    | '/services/quality-control'
    | '/services/quantity-surveying'
    | '/services/renovation'
    | '/services/residential'
    | '/services/site-supervision'
    | '/projects/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  EstimateCalculatorRoute: typeof EstimateCalculatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRoute
  ProjectsAzureHorizonVillaRoute: typeof ProjectsAzureHorizonVillaRoute
  ServicesDesignDrawingsRoute: typeof ServicesDesignDrawingsRoute
  ServicesInteriorDesignRoute: typeof ServicesInteriorDesignRoute
  ServicesProjectManagementRoute: typeof ServicesProjectManagementRoute
  ServicesQualityControlRoute: typeof ServicesQualityControlRoute
  ServicesQuantitySurveyingRoute: typeof ServicesQuantitySurveyingRoute
  ServicesRenovationRoute: typeof ServicesRenovationRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesSiteSupervisionRoute: typeof ServicesSiteSupervisionRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate-calculator': {
      id: '/estimate-calculator'
      path: '/estimate-calculator'
      fullPath: '/estimate-calculator'
      preLoaderRoute: typeof EstimateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/azure-horizon-villa': {
      id: '/projects/azure-horizon-villa'
      path: '/projects/azure-horizon-villa'
      fullPath: '/projects/azure-horizon-villa'
      preLoaderRoute: typeof ProjectsAzureHorizonVillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/design-drawings': {
      id: '/services/design-drawings'
      path: '/services/design-drawings'
      fullPath: '/services/design-drawings'
      preLoaderRoute: typeof ServicesDesignDrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interior-design': {
      id: '/services/interior-design'
      path: '/services/interior-design'
      fullPath: '/services/interior-design'
      preLoaderRoute: typeof ServicesInteriorDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/project-management': {
      id: '/services/project-management'
      path: '/services/project-management'
      fullPath: '/services/project-management'
      preLoaderRoute: typeof ServicesProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/quality-control': {
      id: '/services/quality-control'
      path: '/services/quality-control'
      fullPath: '/services/quality-control'
      preLoaderRoute: typeof ServicesQualityControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/quantity-surveying': {
      id: '/services/quantity-surveying'
      path: '/services/quantity-surveying'
      fullPath: '/services/quantity-surveying'
      preLoaderRoute: typeof ServicesQuantitySurveyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/renovation': {
      id: '/services/renovation'
      path: '/services/renovation'
      fullPath: '/services/renovation'
      preLoaderRoute: typeof ServicesRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/services/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/site-supervision': {
      id: '/services/site-supervision'
      path: '/services/site-supervision'
      fullPath: '/services/site-supervision'
      preLoaderRoute: typeof ServicesSiteSupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  EstimateCalculatorRoute: EstimateCalculatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ProjectsProjectSlugRoute: ProjectsProjectSlugRoute,
  ProjectsAzureHorizonVillaRoute: ProjectsAzureHorizonVillaRoute,
  ServicesDesignDrawingsRoute: ServicesDesignDrawingsRoute,
  ServicesInteriorDesignRoute: ServicesInteriorDesignRoute,
  ServicesProjectManagementRoute: ServicesProjectManagementRoute,
  ServicesQualityControlRoute: ServicesQualityControlRoute,
  ServicesQuantitySurveyingRoute: ServicesQuantitySurveyingRoute,
  ServicesRenovationRoute: ServicesRenovationRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesSiteSupervisionRoute: ServicesSiteSupervisionRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
